### PR TITLE
Fix #181 Make bulk update not fail on annotate and order_by

### LINKED ISSUE #181: Table bulk operation fail when queryset is sorted by an annote field
The bulk post handler fails if the queryset of a Table is ordered by an attribute defined by an django query annotate.

### PR DESCRIPTION
**Pull request by jlubcke**

### CODE REVIEW

**Comment by jlubcke** [comment]
I made a small tweak so that the `pks` callback arg is forced to be evaluated to the actual set of identified modified by the bulk operation.

**Comment by boxed** [comment]
Hmm. Not so keen on the pks thing. If the queryset is truly huge you're gonna have a bad time.

**Comment by jlubcke** [comment]
The diff here is essentially what is going in our local codebase for now. I'll see where it takes us. My guess is that the strict observabillity trumps the performance hit.

**Comment by boxed** [comment]
Maybe. Unless you crash because you're out of memory :P

**Pull request merged**
