### PR TITLE
Make table.rows do one thing and introduce new names for the other things.

### PR DESCRIPTION
**Pull request by bgrundmann**
Idea: Introduce separate fields for the different stages (initial rows, sorted rows, filtered rows, visible rows).

Why is that good?  Because it means we bind / set each field once and the semantics does not depend on where we are in the life-cycle of the table object (mutation is evil).

Indeed I ended up writing this patch because I had a bug trying to write a different patch, which happened because
I hadn't realized that self.paginator is used to rewrite self.rows to be just the visible rows.

As much as table.rows is considered to be a public API it changes the API (see the change in one of the tests).  Now
it didn't seem to have a clearly documented semantics so maybe this is fine.  At the moment I also haven't documented
the new fields.  Which is fine as long as table is primarily there as a way to display values and not to get them out
again.  But we could also consider documenting the fields better.

Testing: All tests still pass.  Also the table examples seem to still behave the same as before (but I only did
some superficial testing, without trying to exhaustively hit every interaction on every page).

### CODE REVIEW

**Comment by boxed** [comment]
One could have a property `rows` which returns the "latest" of those fields that is available, keeping backwards compatibility and meaning you can debug easily (since all the stages exists), and you can specifically ask for one of them if you want, and still keep the ease of use of `.rows`.

**Comment by bgrundmann** [comment]
And add initial_rows early?

**Comment by bgrundmann** [comment]
Those changes are done.  I think this patch is ready to be merged.  Let me know what you think.

**Comment by boxed** [comment]
We've discussed it and we like it. There's some TODOs and comments still in there, but we'll clean them up later.

**Pull request merged**
